### ISSUE TITLE
Random bot link

### ISSUE THREAD

**Issue by hugovk** [botwiki/botwiki.org#35]
How about a link in the menu (or somewhere) to take you to a random bot page?

A bit like Wikipedia has https://en.wikipedia.org/wiki/Special:Random

**Comment by stefanbohacek** [comment]
Yes, this occurred to me as well -- actually, I was also thinking about something along the lines of showing a random bot preview thumbnail on the main page (that would take you to the corresponding bot page).

A typical comment from the [Peek/User Testing](http://peek.usertesting.com/) videos is that the site looks a bit bland and I thought that would be one way to address that.

I guess the only problem with this would be that you'd still need that separate _Random Bot_ link, so you don't have to keep going back to the main page, but I think having both would be alright.

Hmm, I'm trying to think what the best placement for the _Random Bot_ link would be. Maybe we could have a link (either with or without the thumbnail) on the main page and then after that on bot pages under tags?

That would sort of make sense -- "click here to browse by tag, or get a random bot".

Something like:

> Browse more bots like this: **#kik #kikbot #active #news #trending #buzzfeed**
> Or click **here** to get a random one.

I definitely don't want to complicate the menu, and hmm, footer wouldn't be too bad, but I wonder if many people would see it there.

**Comment by hugovk** [comment]
In the menu after Bots?

> [About]() [Events]() [Bots]() [Random Bot]() [Tutorials]() [Resources]() [Articles]()

---

> Something like:
> 
> > Browse more bots like this: **#kik #kikbot #active #news #trending #buzzfeed**
> > Or click **here** to get a random one.

Looks good.

**Comment by stefanbohacek** [comment]
> In the menu after Bots?

Yeah, I am  not a huge fan of adding anything new to the menu at this point, I'd really like to keep that area simple.

I do like my idea above, though. One more thing -- this is an idea I already dismissed, but would love to hear a second opinion.

I was thinking about adding a `#bot` tag to all the `.md` files with bots. This way you could browse _all_ bots.

Now, without a pagination, this would be an overkill. (We do have lazy image loading, though, which is nice.) Maybe it would make sense to just add pagination (we can use [this](https://github.com/rewdy/Pico-Pagination))

I guess I only dismissed this because of the time it would require to make sure that the plugin would work right, and focused on creating categories (links to `/tag/TAG1+TAG2+TAG3` with optional snippets). 

So unless you disagree, I can open an issue for myself to add the pagination plugin.

**Comment by hugovk** [comment]
No disagreements!

**Comment by stefanbohacek** [comment]
@hugovk [botwiki.org/random-bot](https://botwiki.org/random-bot/)!

**Comment by stefanbohacek** [comment]
@hugovk 

Here are the locations of the Random Bot link:

On [botwiki.org/bots](https://botwiki.org/bots/).

![image](https://cloud.githubusercontent.com/assets/3909390/17656228/7d7982d4-6285-11e6-974a-ea33985f6820.png)

In the sidebar:

![image](https://cloud.githubusercontent.com/assets/3909390/17656238/95bf7fec-6285-11e6-8b55-2362d3ac45c2.png)

Under tags on any bot page:

![image](https://cloud.githubusercontent.com/assets/3909390/17656245/a9c45af8-6285-11e6-9381-d08bb0ed3e69.png)

Unless you have any suggestions/comments, I'm closing this issue.

**Comment by hugovk** [comment]
Brilliant! :+1:
